language: node_js
node_js:
- stable
sudo: false
install:
- yarn install
before_script:
- yarn run bumpr check
script:
- yarn test
- yarn run bumpr bump
after_success:
- VERBOSE=1 yarn run bumpr publish
