language: node_js
node_js:
- stable
sudo: false
install:
- yarn install
before_script:
- yarn run bumpr check
script:
- yarn test
- yarn run bumpr bump
after_success:
- VERBOSE=1 yarn run bumpr publish
env:
  global:
  - secure: iPd1b01qzxQbUBXnYZkxpNK1VdcsGutDeZ6z3QsZTgAuebOrRbJmwCBiWkRBt171rZNFN0g8Qcsr9doym85b285CyR5ZKrOdIVyTyORFfBGXTnc6XIfX4X4x0yr3+NhYvUkyJXE9dyEBMQQK9JA8LpJ8rmJhtji4kYDU7oJxOoz2pJLgfksATk7qMXHFe/KmTdbxElkbA/DNwS1GNvj7aLJALxSU+4ZSVXHVMbxVa84huRayTUO78VT2k9p4rphot+6QKKRzXOFOVPD7h3Mvo3xGEVde3ZMDCZGD6TnE3R7ffzXhdy/fTKpUF6D4pkONEC/64SOxlW5127enS5hwOC1xw/o+dOrH1UH7S8GYWN/2k7LPOYlosi2QUhnObEW0WEV6EakdHgRxFWFvaAq/HKV8cNkAZJiHxIDifN9LrZqeePj9B8ctHU3j+xjmIp67jMtDoTdAgErrCuJeEPFtSamD95UGGikhSuQKXAnxdb5mGhnDVyvE3E8pScoClld2t/kiYXo9o/ASCBhReXHoGIyggsLo0puKOqP9J48hxSH4OJpQRjPIBbvygvB3PAVtkM50Q/mhu7k00pOcsDanlnJvz9puGR9UgY4fqNJJF9JuIgfuDW/oN9oay9+GW9U7oLYGfyQON/AAvyfM2rQa7TCji3Uwj2PhqAdqcz9HV54=
  - secure: H1IlXVXo8WgbEgNHdUp2XLwzpjConciXVBZOFgSxADvLgmZqmZjVJyjODJm2olFzVUGc/vUU5DdPzRKsjvHu48/9XjIWim7Vz1vPFOl94IMeMVTMWZfW7JQ2kiZ2jCmhNKVyXiHOOI8p3bNmG3FOpg2yjxip5mYnDfkt/edInW8C51WW0BOAc7sVn1FImyrPWk2ejv4ozOs4wHqVeQtMPu+yUZrN4FbClFze3/Z6KR37TcUXNazKjSglJbq1RrlRe8WenpvOfHd8M+bo6dqweUDWISGTJxRTLtCgFMRU47PDLS+DUivgBPiV2O7jxPt+x8VwRgDwXE36PqSdF99hJmgeFSSeF6W1H9I9k1Z9d0MUeoIwYqjSnSki95KJnfgHBsykI2Ube8d2hEBqt6ElTkGUeZyEC3RrVke403go0pLoPpIXwwIsBXw4XpCCDnITxJnULTtij/W6F0wYPxxit3bCADfGipGMWHJSPFK/EsD6jX6dl9HjhrwgM0eDsymsoGGHX4Gxs4CAmLpiXKA3i++yjBZu7YadVfeoP3g8YdkVhtW1agxGjonlqYex/Xbbn2FRitgNY0zg7FTC4LZAn3hBmwkMZ06nCeT7SVJ8I5eNK2fsiK8a0S08oiYf3CnugvYm0RoPi8JvUBvKQHb1p4nsneOwc6FkaG0ZEDEMNSU=
